
const Set_Pokemon = 'Set_Pokemon';
const FAVORITE_POKEMON = 'FAVORITE_POKEMON';
const CLICK_FAVORITE = 'CLICK_FAVORITE';
const LOADER = 'LOADER';
const VER_FAVORITOS = 'VER_FAVORITOS';
const FALSE_FAVORITE = 'FALSE_FAVORITE';
const NUMERO_BUSQUEDA = 'NUMERO_BUSQUEDA';
const SET_POKEMON_BUSCADO = 'SET_POKEMON_BUSCADO';

export { Set_Pokemon, FAVORITE_POKEMON, CLICK_FAVORITE, LOADER, VER_FAVORITOS, FALSE_FAVORITE, NUMERO_BUSQUEDA, SET_POKEMON_BUSCADO };




